services:
  backend:
    build: 
    context: ./mern/backend
    dockerfile: Docherfile
    container_name: backend
    ports:
      - "8000:8000" 
    environment:
      - MongoDB_URI=mongodb://mongo:27017/merndb
    networks:
      - mtvpc
    depends_on:
      - mongodb

  frontend:
    build: 
    context: ./mern/frontend
    dockerfile: Docherfile
    container_name: frontend
    ports:
      - "5173:5173"  
    networks:
      - mtvpc
   

  mongodb:
    image: mongo:latest  
    container_name: mongo
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mtvpc:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

